services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    healthCheckPath: /
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: password123
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
